### ISSUE TITLE
Problems with issuing an invitation

### ISSUE THREAD

**Issue by johnhemming** [hmrc/agent-invitations-frontend#430]
I am creating a test agent, authorising my software through OAuth for sending an invitation then sending an invitation, but getting a "session record not found" 401 error which I presume is the SessionRecordNotFound exception.   What should I do?

Moreso in the sense of who should I speak to. I have emailed SDST (at their new address) and they have said they cannot recreate the error.

**Comment by JTY009** [comment]
Hi @johnhemming can you please tells us the steps you made? so we can debug on our side

**Comment by johnhemming** [comment]
I have a test bed that creates a new agent, then authorises my software using oauth (which it does for the scope sent-invitations ) and then runs:
https://test-api.service.hmrc.gov.uk/agents/GARN0313812/invitations
With a JSON string of:
{"service": ["MTD-IT"], "clientType":"personal", "clientIdType": "ni", "clientId": "SW724953C", "knownFact": "RM85 0VL"	}

I have just run this.  I would be happy to give you the IP address from which this is running and I could allow you access to my test bed so you can run it (although it has to be switched on), but I don't want to do that via github.  Best to email me and establish a direct email contact.
I have just run it (twice actually, the first time oauth failed, the second time it worked).

**Comment by johnhemming** [comment]
I got this response:
401 Unauthorized {"statusCode":401,"message":"Session record not found"} 401 error message

**Comment by JTY009** [comment]
Hi @johnhemming apologises for late reply. what is the best email to use to contact you? We will investigate and get back to you as soon as possible.

**Comment by JTY009** [comment]
Also I cannot help wondering. Is this an issue for the Agent Authorization Api: https://github.com/hmrc/agent-authorisation-api? not this particular repo?

**Comment by johnhemming** [comment]
You might be right about that.   It relates to agents authorisations.   My email is john@hemming.email anyway.

**Comment by johnhemming** [comment]
However, it is running the invitations rest method so It might be here as well.

**Comment by johnhemming** [comment]
I find a reference to it here:
https://github.com/hmrc/agent-subscription-frontend/blob/master/it/uk/gov/hmrc/agentsubscriptionfrontend/stubs/AuthStub.scala

**Comment by JTY009** [comment]
Hi @johnhemming, we will continue this issue via email

**Comment by johnhemming** [comment]
This was my error and I thank Paul for assisting me and resolving it.
