### ISSUE TITLE
Problems issuing an invitation version 2

### ISSUE THREAD

**Issue by johnhemming** [hmrc/agent-invitations-frontend#438]
Further to the previous solved problem.
I am trying to use the create authorisation API.

Initially what worked a couple of days ago didn't work.  I assumed that the test data may have been deleted so I went in and recreated a test user.

After that when I tried to create an invitation for the test agent the IT one worked,  but the VAT one didn;t
The IT JSON is {"service": ["MTD-IT"], "clientType":"personal", "clientIdType": "ni", "clientId": "SW724953C", "knownFact": "RM85 0VL"	}

The VAT JSON is: {"service": ["MTD-VAT"], "clientType":"business", "clientIdType": "vrn", "clientId": "242379068", "knownFact": "1980-05-30"}
second attempt: {"service": ["MTD-VAT"], "clientType":"business", "clientIdType": "vrn", "clientId": "242379068", "knownFact": "RM85 0VL"}

I am going by the specification which gives the VAT number as the client ID which is from the test data.  The "known fact" for VAT I presume is actually the VAT registration date going from the Spec.  I found that date on another page for the test user and it also referred to the post code as being a known fact.  Hence I tried both of those.  I also tried a clientType of personal. All of these gave a 400 bad request error.

Separately as I have managed to get one 204 message I thought I would see if I could agree the invitation hence I found the URL
https://test-www.tax.service.gov.uk/invitations/{clientType}/{uid}/{agent-name}
And I tried that as:
https://test-www.tax.service.gov.uk/invitations/personal/5b3a7b3e-bc8d-4276-890f-35de2dff2ebe/Shawn Newton
Which didn't work so I tried it as :
https://test-www.tax.service.gov.uk/invitations/personal/5b3a7b3e-bc8d-4276-890f-35de2dff2ebe/WARN0265467

That also redirected to this URL
https://test-www.tax.service.gov.uk/invitations/not-found/

Hence this is sort of two issues, but it really relates to one issue viz getting invitations to work hence the single item.

TIA.

**Comment by johnhemming** [comment]
Further to this just to see what happens I tried to use the location given by the create invitation API
https://test-www.tax.service.gov.uk/agents/YARN0726304/invitations/AT49A5NH8RPMS
and I got "not implemented" which is fair enough.

**Comment by johnhemming** [comment]
Further to the latter part of the above, however, I have found a solution.  When I looked at the response from the get list of relationships I found
https://test-www.tax.service.gov.uk/invitations/personal/GZLYDMFB/james-accountancy

I am not sure how to find this out other than from there. However, that does seem to do the right sort of thing.  Hence we are now down to the one sub-issue about VAT.

This is, however, sufficient now so that I can start writing a front end to this.

**Comment by sarthak83** [comment]
Hi John, Let me try to address both of your issues 

Issue 1. Creating VAT Failed. Your Json appears to be fine. We will investigate what has gone wrong. If MTD-IT has worked, its literally the same endpoint for VAT with the updated Json. Can I ask you to try the same call which has worked for you for MTD-IT, but with this Json 
`{"service": ["MTD-VAT"], "clientType":"business", "clientIdType": "vrn", "clientId": "242379068", "knownFact": "1980-05-30"}`

Issue 2: Unable to accept your invitation. It appears, the way you are constructing the URL is not correct. 
`https://test-www.tax.service.gov.uk/invitations/personal/5b3a7b3e-bc8d-4276-890f-35de2dff2ebe/Shawn Newton`
If you see the help guide, https://test-www.tax.service.gov.uk/agents-external-stubs/help/agent-authorisation-api , under **Create agent-client relationship in agents-external-stubs->Prerequisites**, You have to do a GET call on the created invitation and use the link returned in **clientActionUrl** element. The agencyName and UID are uniquely generated and normalised and the only way to retrieve it is by the GET call. Can you please use the clientActionUrl. 

Your sequence of steps would be 

- Create an Invitation using a POST call
- Do a GET on the created invitation
- Copy the clientActionUrl from the response 
- Navigate to the url in the browser
- Sign in as the client you created as userID for which you have created the invitation (planet: hmrc)
- Go through the journey and accept the invitation.

**Comment by johnhemming** [comment]
I have just run this again and using the clientActionUrl I can find both the IT and the VAT invitations awaiting a response. Thank you for your assistance in closing this issue.

I am now I think in a position to write the front end for this so I will get on with that.
